---
# This playbook will install clients for openvpn

- name: Create client certificate
  shell: . ./vars && ./pkitool --batch {{ item }}
  args:
    chdir: /etc/openvpn/easy-rsa
    creates: keys/{{ item }}.csr
  with_items: "{{ VpnClients }}"

- name: Get public IP address for OpenVPN host
  command: "dig +short myip.opendns.com @resolver1.opendns.com"
  changed_when: false
  register: "RemoteHost"

- name: Create client configuration files
  template:
    src: client.conf.j2
    dest: /etc/openvpn/easy-rsa/keys/{{ ServerName }}-{{ item }}.conf
    mode: 0644
  with_items: "{{ VpnClients }}"

- name: Make an ovpn copy of the client files
  copy:
    src: /etc/openvpn/easy-rsa/keys/{{ ServerName }}-{{ item }}.conf
    dest: /etc/openvpn/easy-rsa/keys/{{ ServerName }}-{{ item }}.ovpn
    mode: 0644
    remote_src: yes
  with_items: "{{ VpnClients }}"

- name: Create tar for client configuration
  archive:
    path:
      - /etc/openvpn/easy-rsa/keys/{{ ServerName }}-{{ item }}.conf
      - /etc/openvpn/easy-rsa/keys/{{ ServerName }}-{{ item }}.ovpn
      - /etc/openvpn/easy-rsa/keys/{{ item }}.key
      - /etc/openvpn/easy-rsa/keys/{{ item }}.crt
      - /etc/openvpn/easy-rsa/keys/ca.crt
    dest: /etc/openvpn/easy-rsa/keys/{{ item }}.tar.gz
    format: gz
    mode: 0600
  with_items: "{{ VpnClients }}"
